apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: randomstring-pinpong-claim
  namespace: exercises
spec:
  storageClassName: my-randomstrings-pingpong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
