apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pingpong-dep
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3001
