apiVersion: v1
kind: ConfigMap
metadata:
  name: todoapp-config
  namespace: project
data:
  PORT: "3000"
  TODO_BACKEND_URL: "http://todo-backend-svc"
  CACHE_DIR: "/usr/src/app/data"
  IMAGE_SOURCE_URL: "https://picsum.photos/1200"
  TTL_MS: "600000"
