apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp-dep
  template:
    metadata:
      labels:
        app: todoapp-dep
    spec:
      volumes:
        - name: images-data
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp-dep
          image: borisbanchev03/todo-app-initial:v1.0.6
          envFrom:
            - configMapRef:
                name: todoapp-config
          volumeMounts:
            - name: images-data
              mountPath: /usr/src/app/data
