apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todoapp-dep
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
