apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: exercises-shared-route
  namespace: exercises
spec:
  parentRefs:
    - name: my-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      backendRefs:
        - name: pingpong-svc
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /randomstrings/strings
      backendRefs:
        - name: randomstrings-svc
          port: 3003
    - matches:
        - path:
            type: PathPrefix
            value: /randomstrings
      backendRefs:
        - name: randomstrings-svc
          port: 80
