apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  MESSAGE: "hello this is env from log output application"
  information.txt: |
    this is information from log output application
