apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomstrings-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomstrings-dep
  template:
    metadata:
      labels:
        app: randomstrings-dep
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: log-generator
          image: borisbanchev03/kubernetes-app1:v1.0.4
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: log-reader
          image: borisbanchev03/logoutput-reader:reader.v2
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
