apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomstrings-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomstrings-dep
  template:
    metadata:
      labels:
        app: randomstrings-dep
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: randomstring-pinpong-claim
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: log-generator
          image: borisbanchev03/kubernetes-app1:v1.0.14
          ports:
            - name: generator
              containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/configdata
              readOnly: true
            - name: shared-data
              mountPath: /usr/src/app/data
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE

        - name: log-reader
          image: borisbanchev03/logoutput-reader:reader.v7
          ports:
            - name: reader
              containerPort: 3003
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
