apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomstrings-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomstrings-dep
  template:
    metadata:
      labels:
        app: randomstrings-dep
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: randomstring-pinpong-claim
      containers:
        - name: log-generator
          image: borisbanchev03/kubernetes-app1:v1.0.8

        - name: log-reader
          image: borisbanchev03/logoutput-reader:reader.v3
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
        - name: ping-pinpong
          image: borisbanchev03/kubernetes-app3:v1.0.2
          ports:
            - containerPort: 3001
