apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomstrings-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: randomstrings-svc
                port:
                  number: 2345
          - path: /strings
            pathType: Prefix
            backend:
              service:
                name: randomstrings-svc
                port:
                  number: 3003
