apiVersion: v1
kind: Service
metadata:
  name: randomstrings-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: randomstrings-dep
  ports:
    - name: generator
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: reader
      port: 3003
      protocol: TCP
      targetPort: 3003
