apiVersion: v1
kind: Service
metadata:
  name: hashresponse-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: hashresponse-dep
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
