apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todoapp-claim
  namespace: project
spec:
  storageClassName: my-todoapp-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
